import React from "react";
import Meta from "../../components/meta";

const Contact = () => {
  return (
    <div>
      <Meta
        title="Contact"
        name='description" content'
        content="Generated by create next app"
      />
      <h1>Contact</h1>
    </div>
  );
};

export default Contact;
