import React from "react";
import Meta from '../../components/meta';

const About = () => {
  return (
    <div>
      <Meta
        title="About"
        name='description" content'
        content="Generated by create next app"
      />
      <h1>About</h1>
    </div>
  );
};

export default About;
