import React from "react";
import Meta from '../../components/meta';

const About = () => {
  return (
    <div className="text-red-400">
      <Meta
        title="About"
        name='description" content'
        content="Generated by create next app"
      />
    </div>
  );
};

export default About;
