import Meta from "../components/meta";
// import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Meta
        title="HOME"
        name='description" content'
        content="Generated by create next app"
      >
        <link rel="icon" href="/favicon.ico" />
      </Meta>
      <h1>Home Page</h1>
    </div>
  );
}
