import React from "react";
import Meta from "../../components/meta";

const Courses = () => {
  return (
    <div>
      <Meta
        title="Courses"
        name='description" content'
        content="Generated by create next app"
      />
      <h1>Courses</h1>
    </div>
  );
};

export default Courses;
